# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
        - develop
 
    docker:
      # specify the version you desire here
      - image: circleci/node:12.14.1
    environment:
      IMAGE_NAME: relovely/relovely-web
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
 
    working_directory: ~/relovely-app
 
    steps:
 
      - checkout
      - setup_remote_docker
      - run:
          name: Set IP
          command: |
            if [ $CIRCLE_BRANCH = 'develop' ]; then
              CURRENT_DROPLET_IP=$DEVELOPMENT_DROPLET_IP
            elif [ $CIRCLE_BRANCH = 'master' ]; then
              CURRENT_DROPLET_IP=$DROPLET_IP
            fi
            echo "export CURRENT_DROPLET_IP=$CURRENT_DROPLET_IP" >> $BASH_ENV
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no root@$CURRENT_DROPLET_IP bash -c '
            sudo cat ~/password.txt | docker login --username relovely --password-stdin;
            sudo docker stop $(docker ps -a -q);
            sudo docker rm -f $(docker ps -a -q);
            sudo docker rmi -f $(docker images -q);
            sudo docker pull $IMAGE_NAME:latest;
            sudo docker run -d --network host $IMAGE_NAME'
 
      ################ WARNING WARNING #####################
      # doing no strict host key check is a security risk to some extent.
      # But I haven't figured a way to add to ssh for both CI and DO to communicate without that
      # message popping up 